graficos:
    pattern:  /
    defaults: { _controller: "ConfigOrionBundle:graficos:index" }

graficos_spline:
    pattern:  /spline
    defaults: { _controller: "ConfigOrionBundle:graficos:spline" }

graficos_filter:
    pattern:  /filtrar
    defaults: { _controller: "ConfigOrionBundle:graficos:filter" }
    requirements: { _method: post|put }


graficos_filter_spline:
    pattern:  /spline/filtrar
    defaults: { _controller: "ConfigOrionBundle:graficos:filterSpline" }
    requirements: { _method: post|put }

